---
version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"

  site:
    build:
      dockerfile: Dockerfile
      context: ./
    expose:
      - "8080"
    networks:
      - default

  nginx:
    image: nginx
    ports:
      - "443:443"
    networks:
      - default
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/snakeoil.crt:/etc/nginx/ssl/snakeoil.crt:ro
      - ./docker/snakeoil.key:/etc/nginx/ssl/snakeoil.key:ro
